#!/bin/bash

declare -r RED="\e[91m"
declare -r GREEN="\e[92m"
declare -r YELLOW="\e[93m"
declare -r BLUE="\e[94m"
declare -r PURPLE="\e[95m"
declare -r CYAN="\e[96m"
declare -r WHITE="\e[97m"
declare -r END="\e[0m"

declare -r VAR1='['
declare -r VAR2=']'
declare -r VAR3='i'
declare -r VAR4='*'
declare -r VAR5='>'
declare -r VAR6='<'
declare -r VAR7='-'
declare -r VAR8='+'
declare -r VAR9='rsync-brute'
declare -r VAR10='Installing rsync tool.'
declare -r VAR11='WORDLIST'
declare -r VAR12='Use:'
declare -r VAR13='TARGET'
declare -r VAR14='Wordlist:'
declare -r VAR15='Found:'
declare -r VAR16='Line:'
declare -r VAR17='Error!'
declare -r VAR18='Fuck!'
declare -r VAR19='no resources found.'
declare -r VAR20='rsync not installed.'
declare -r VAR21='Status:'
declare -r VAR22='-============================-'
declare -r VAR23='Target:'
declare -r VAR24='PORT'

declare -r BOX1="$WHITE$VAR1$GREEN$VAR8$WHITE$VAR2$END"
declare -r BOX2="$WHITE$VAR1$RED$VAR7$WHITE$VAR2$END"
declare -r BOX3="$WHITE$VAR1$YELLOW$VAR3$WHITE$VAR2$END"
declare -r BOX4="$WHITE$VAR1$BLUE$VAR4$WHITE$VAR2$END"

trap ctrl_c INT

function check(){
    which rsync > /dev/null 2>&1
  if [ "$(echo $?)" == "0" ]; then
    :
  else
    echo ""
    echo -e "$BOX2 $REDEXIT$VAR17 $WHITE$VAR20$END"
    echo ""
    sleep 2
    echo -e "$BOX1 $WHITE$VAR10$END"
    apt-get install rsync -y &>/dev/null
    sleep 2
    return
  fi
}

function banner(){      
  echo -e "$GREEN   _ __ ___ _   _ _ __   ___ $END"
  echo -e "$GREEN  | '__/ __| | | | '_ \ / __|$END"
  echo -e "$GREEN  | |  \__ \ |_| | | | | (__ $END"
  echo -e "$GREEN  |_|  |___/\__, |_| |_|\___|$END"
  echo -e "$RED   _        $GREEN |___/ $RED _$END"
  echo -e "$RED  | |__  _ __ _   _| |_ ___  $END"
  echo -e "$RED  | '_ \| '__| | | | __/ _ \ $END"
  echo -e "$RED  | |_) | |  | |_| | ||  __/ $END"
  echo -e "$RED  |_.__/|_|   \__,_|\__\___| $END"
  echo -e "$WHITE$VAR22$END"
}

function help(){
  echo ""
  echo -e "$BOX3 $RED$VAR12 $WHITE$VAR9 -t $RED$VAR6$WHITE$VAR13$RED$VAR5$WHITE -w $RED$VAR6$WHITE$VAR11$RED$VAR5$WHITE$END"
  echo ""
}

function info(){
  echo -e " $BOX4 $WHITE$VAR23   $BLUE$TARGET$WHITE$END"
  sleep 1
  echo -e " $BOX4 $WHITE$VAR14 $BLUE$WORDLIST$END"
  sleep 1
  echo -e " $BOX3 $WHITE$VAR21$END"
  sleep 1
}

function ctrl_c(){
  echo ""
  exit 1
}

while getopts ":w:t:" arg; do
  case $arg in
    w) WORDLIST=$OPTARG; let parameter_counter+=1 ;;
    t) TARGET=$OPTARG; let parameter_counter+=1 ;;
  esac
done

if [ ! -z $TARGET ]; then
  check
  banner
else
  check
  banner
  help
  exit 0
fi

if [ ! -z $WORDLIST ]; then
  info
else
  help
  exit 0
fi

LINES=$(wc -l $WORDLIST)
REGEX="([0-9]+).$WORDLIST"
[[ $LINES =~ $REGEX ]]
SIZ="${BASH_REMATCH[1]}"

while read RESOURCE; do
    LINE=$((LINE + 1))
    PROGRESS=$((LINE * 100 / SIZ))
    echo -ne "\r     $YELLOW$LINE/$SIZ/$PROGRESS%/$RESOURCE                                    $END"
    rsync $TARGET::$RESOURCE &>/dev/null
  if [ $? -eq 0 ]; then
    F1=$(/usr/bin/cat $WORDLIST | grep "^$RESOURCE$" -n | cut -d ":" -f 1)
    echo -e "\n $BOX1 $RED$VAR15 $GREEN$RESOURCE$RED $VAR16 $GREEN$F1$END"
    echo ""
    sleep 2
    exit 0
  fi
done < $WORDLIST
echo -e "\r $BOX2 $RED$VAR18 $WHITE$VAR19$END"
echo ""
sleep 2
exit 0
